### ISSUE TITLE
切换的时候会自动勾选偏好设置里的新建数据，使用英文插件的时候勾选此选项常常报错

### ISSUE THREAD

**Issue by hzc54188** [scifx/blender-language-switcher#1]
![image](https://github.com/scifx/blender-language-switcher/assets/24639554/2e6ea1b1-dba8-4692-bb27-f5f5dbd759c5)

**Comment by scifx** [comment]
感谢反馈！看来还有工作需要做呢

**Comment by scifx** [comment]
> ![image](https://user-images.githubusercontent.com/24639554/245455203-2e6ea1b1-dba8-4692-bb27-f5f5dbd759c5.png)

@hzc54188 新版本已经修复了！
